name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build poppler
        run: |
          make distribution
      - name: Upload the artifacts
        uses: actions/upload-artifact@v2
        with:
          name: poppler
          path: export/poppler.zip
      - name: Publish the artifacts
        uses: fnkr/github-action-ghr@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GHR_PATH: export/poppler.zip
